apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealie
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
